variables:
  UV_THREADPOOL_SIZE: "100"

stages:
   - build
   - deploy

build:
  stage: build
  tags: [linux, docker, k8]
  image: node:boron
  script:
    - tar -cvzf ctrl-oidc-transformer.tar.gz .
  artifacts:
    name: ctrl-oidc-transformer
    paths:
      - .

deploy_branch:
  when: manual
  stage: deploy
  tags: [linux, docker, k8]
  image: ctrlhub-deloitte.azurecr.io/in/deploy-webapp:latest
  script:
    - deploy-webapp -e $CI_COMMIT_REF_NAME ./ ctrl-oidc-transformer
  except:
    - master
    - tags

deploy:version:
  stage: deploy
  tags: [linux, docker, k8]
  image: ctrlhub-deloitte.azurecr.io/in/deploy-webapp:latest
  script:
    - deploy-webapp -e $CI_COMMIT_REF_NAME ./ ctrl-oidc-transformer
  only:
    - master
    - tags